/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    labs: Lab;
    proyectos: Proyecto;
    publicaciones: Publicacion;
    entradas: Entrada;
    noticias: Noticia;
    centros: Centro;
    personas: Persona;
    organizaciones: Organizacion;
    categorias: Categoria;
    media: Media;
    documentos: Documento;
    'mensajes-contacto': MensajeContacto;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    labs: LabsSelect<false> | LabsSelect<true>;
    proyectos: ProyectosSelect<false> | ProyectosSelect<true>;
    publicaciones: PublicacionesSelect<false> | PublicacionesSelect<true>;
    entradas: EntradasSelect<false> | EntradasSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    centros: CentrosSelect<false> | CentrosSelect<true>;
    personas: PersonasSelect<false> | PersonasSelect<true>;
    organizaciones: OrganizacionesSelect<false> | OrganizacionesSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documentos: DocumentosSelect<false> | DocumentosSelect<true>;
    'mensajes-contacto': MensajesContactoSelect<false> | MensajesContactoSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    sitio: Sitio;
  };
  globalsSelect: {
    sitio: SitioSelect<false> | SitioSelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labs".
 */
export interface Lab {
  id: number;
  nombre: string;
  /**
   * Identificador en la URL (sin espacios ni acentos).
   */
  slug: string;
  orden?: number | null;
  descripcion: string;
  introduccion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  imagen?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  credito?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos".
 */
export interface Proyecto {
  id: number;
  titulo: string;
  /**
   * Identificador en la URL (sin espacios ni acentos).
   */
  slug: string;
  lab: number | Lab;
  descripcion: string;
  autores?: string | null;
  anio?: string | null;
  lugar?: string | null;
  participantes?: string | null;
  categorias?: (number | Categoria)[] | null;
  fotos?: (number | Media)[] | null;
  secciones?:
    | {
        titulo: string;
        cuerpo?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        subsecciones?:
          | {
              titulo: string;
              cuerpo?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  descargable?: {
    etiqueta?: string | null;
    archivo?: (number | null) | Documento;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  nombre: string;
  /**
   * Identificador en la URL (sin espacios ni acentos).
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos".
 */
export interface Documento {
  id: number;
  titulo: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicaciones".
 */
export interface Publicacion {
  id: number;
  titulo: string;
  /**
   * Identificador en la URL (sin espacios ni acentos).
   */
  slug: string;
  tipo: 'reportes' | 'articulos-y-libros' | 'recursos-educativos';
  lab?: (number | null) | Lab;
  descripcion: string;
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  autores?: string | null;
  anio?: string | null;
  paginas?: string | null;
  categorias?: (number | Categoria)[] | null;
  portada?: (number | null) | Media;
  pdf?: (number | null) | Documento;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entradas".
 */
export interface Entrada {
  id: number;
  titulo: string;
  /**
   * Identificador en la URL (sin espacios ni acentos).
   */
  slug: string;
  tipo: 'blog' | 'comunicados' | 'cobertura-de-prensa' | 'noticias-del-observatorio';
  fecha: string;
  descripcion: string;
  contenido?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  creditos?: string | null;
  participantes?: string | null;
  /**
   * Medio de comunicación (cobertura de prensa).
   */
  fuente?: string | null;
  categorias?: (number | Categoria)[] | null;
  fotos?: (number | Media)[] | null;
  pdf?: (number | null) | Documento;
  updatedAt: string;
  createdAt: string;
}
/**
 * Corpus de notas de prensa que alimenta el Buscador de Noticias.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: number;
  titulo: string;
  medio: string;
  fecha: string;
  url: string;
  categorias?: (number | Categoria)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "centros".
 */
export interface Centro {
  id: number;
  nombre: string;
  ciudad: string;
  pais: string;
  empresa?: string | null;
  estado: 'en-operacion' | 'en-construccion' | 'anunciado';
  inversionUsdMillones?: number | null;
  lat: number;
  lng: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas".
 */
export interface Persona {
  id: number;
  nombre: string;
  /**
   * Identificador en la URL (sin espacios ni acentos).
   */
  slug: string;
  orden?: number | null;
  equipo?: boolean | null;
  grupo: 'investigacion' | 'comunidad' | 'aliados';
  titulo?: string | null;
  rol?: string | null;
  organizacion?: (number | null) | Organizacion;
  region?: string | null;
  afiliacion?: string | null;
  correo?: string | null;
  biografia?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  foto?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizaciones".
 */
export interface Organizacion {
  id: number;
  nombre: string;
  /**
   * Identificador en la URL (sin espacios ni acentos).
   */
  slug: string;
  region?: string | null;
  web?: string | null;
  correo?: string | null;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mensajes recibidos desde el formulario de contacto del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mensajes-contacto".
 */
export interface MensajeContacto {
  id: number;
  nombre: string;
  correo: string;
  asunto: string;
  mensaje: string;
  leido?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nombre: string;
  rol: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'labs';
        value: number | Lab;
      } | null)
    | ({
        relationTo: 'proyectos';
        value: number | Proyecto;
      } | null)
    | ({
        relationTo: 'publicaciones';
        value: number | Publicacion;
      } | null)
    | ({
        relationTo: 'entradas';
        value: number | Entrada;
      } | null)
    | ({
        relationTo: 'noticias';
        value: number | Noticia;
      } | null)
    | ({
        relationTo: 'centros';
        value: number | Centro;
      } | null)
    | ({
        relationTo: 'personas';
        value: number | Persona;
      } | null)
    | ({
        relationTo: 'organizaciones';
        value: number | Organizacion;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documentos';
        value: number | Documento;
      } | null)
    | ({
        relationTo: 'mensajes-contacto';
        value: number | MensajeContacto;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labs_select".
 */
export interface LabsSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  orden?: T;
  descripcion?: T;
  introduccion?: T;
  imagen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proyectos_select".
 */
export interface ProyectosSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  lab?: T;
  descripcion?: T;
  autores?: T;
  anio?: T;
  lugar?: T;
  participantes?: T;
  categorias?: T;
  fotos?: T;
  secciones?:
    | T
    | {
        titulo?: T;
        cuerpo?: T;
        subsecciones?:
          | T
          | {
              titulo?: T;
              cuerpo?: T;
              id?: T;
            };
        id?: T;
      };
  descargable?:
    | T
    | {
        etiqueta?: T;
        archivo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publicaciones_select".
 */
export interface PublicacionesSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  tipo?: T;
  lab?: T;
  descripcion?: T;
  contenido?: T;
  autores?: T;
  anio?: T;
  paginas?: T;
  categorias?: T;
  portada?: T;
  pdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entradas_select".
 */
export interface EntradasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  tipo?: T;
  fecha?: T;
  descripcion?: T;
  contenido?: T;
  creditos?: T;
  participantes?: T;
  fuente?: T;
  categorias?: T;
  fotos?: T;
  pdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  medio?: T;
  fecha?: T;
  url?: T;
  categorias?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "centros_select".
 */
export interface CentrosSelect<T extends boolean = true> {
  nombre?: T;
  ciudad?: T;
  pais?: T;
  empresa?: T;
  estado?: T;
  inversionUsdMillones?: T;
  lat?: T;
  lng?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas_select".
 */
export interface PersonasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  orden?: T;
  equipo?: T;
  grupo?: T;
  titulo?: T;
  rol?: T;
  organizacion?: T;
  region?: T;
  afiliacion?: T;
  correo?: T;
  biografia?: T;
  foto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizaciones_select".
 */
export interface OrganizacionesSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  region?: T;
  web?: T;
  correo?: T;
  descripcion?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credito?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documentos_select".
 */
export interface DocumentosSelect<T extends boolean = true> {
  titulo?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mensajes-contacto_select".
 */
export interface MensajesContactoSelect<T extends boolean = true> {
  nombre?: T;
  correo?: T;
  asunto?: T;
  mensaje?: T;
  leido?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sitio".
 */
export interface Sitio {
  id: number;
  inicio: {
    titulo: string;
    texto?: string | null;
  };
  quienesSomos?: {
    titulo?: string | null;
    proposito?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    equipoTexto?: string | null;
    organizacionesTexto?: string | null;
    personasTexto?: string | null;
  };
  paginas?: {
    ejesDeTrabajo?: string | null;
    mapa?: string | null;
    mapaResumen?: string | null;
    contacto?: string | null;
  };
  publicaciones?: {
    reportes?: string | null;
    articulosLibros?: string | null;
    recursosEducativos?: string | null;
  };
  actualidad?: {
    blog?: string | null;
    comunicados?: string | null;
    coberturaPrensa?: string | null;
    noticiasObservatorio?: string | null;
  };
  legales?: {
    accesibilidad?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    privacidad?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    terminos?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  redes?: {
    correoContacto?: string | null;
    enlaces?:
      | {
          red: 'instagram' | 'linkedin' | 'facebook';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sitio_select".
 */
export interface SitioSelect<T extends boolean = true> {
  inicio?:
    | T
    | {
        titulo?: T;
        texto?: T;
      };
  quienesSomos?:
    | T
    | {
        titulo?: T;
        proposito?: T;
        equipoTexto?: T;
        organizacionesTexto?: T;
        personasTexto?: T;
      };
  paginas?:
    | T
    | {
        ejesDeTrabajo?: T;
        mapa?: T;
        mapaResumen?: T;
        contacto?: T;
      };
  publicaciones?:
    | T
    | {
        reportes?: T;
        articulosLibros?: T;
        recursosEducativos?: T;
      };
  actualidad?:
    | T
    | {
        blog?: T;
        comunicados?: T;
        coberturaPrensa?: T;
        noticiasObservatorio?: T;
      };
  legales?:
    | T
    | {
        accesibilidad?: T;
        privacidad?: T;
        terminos?: T;
      };
  redes?:
    | T
    | {
        correoContacto?: T;
        enlaces?:
          | T
          | {
              red?: T;
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}